package com.selenium.util;

public class CONFIGKEY {

	// SELENIUM CONFIG KEYS
	public static String BROWSER_TO_TEST = "BROWSER_TO_TEST";
	public static String APP_URL = "APP_URL";
	public static String APP_URL_SAMPLE = "APP_URL_SAMPLE";

	
	public static String CAPTURE_SCREENSHOT_AFTER_CLICK_EVENT = "CAPTURE_SCREENSHOT_AFTER_CLICK_EVENT";
	public static String RUN_WEB_SCRIPT_ON_LOCAL = "RUN_WEB_SCRIPT_ON_LOCAL";

	public static String RUN_MOBILE_SCRIPT_ON_SAUCELAB = "RUN_MOBILE_SCRIPT_ON_SAUCELAB";
	public static String TEST_OBJECT_API_KEY = "TEST_OBJECT_API_KEY";
	public static String SAUCELAB_APPIUM_HUB_URL = "SAUCELAB_APPIUM_HUB_URL";

	public static String RUN_MOBILE_SCRIPT_ON_BROWSERSTACK = "RUN_MOBILE_SCRIPT_ON_BROWSERSTACK";
	public static String BROWSERSTACK_USERNAME = "BROWSERSTACK_USERNAME";
	public static String BROWSERSTACK_AUTOMATE_KEY = "BROWSERSTACK_AUTOMATE_KEY";
	public static String BROWSERSTACK_ANDROID_MOBILE_DEVICES = "BROWSERSTACK_ANDROID_MOBILE_DEVICES";
	public static String BROWSERSTACK_ANDROID_TABLET_DEVICES = "BROWSERSTACK_ANDROID_TABLET_DEVICES";
	public static String BROWSERSTACK_IOS_MOBILE_DEVICES = "BROWSERSTACK_IOS_MOBILE_DEVICES";
	public static String BROWSERSTACK_IOS_TABLET_DEVICES = "BROWSERSTACK_IOS_TABLET_DEVICES";

	public static String RUN_MOBILE_SCRIPT_ON_CROSSBROWSERTESTING = "RUN_MOBILE_SCRIPT_ON_CROSSBROWSERTESTING";
	public static String CROSSBROWSERTESTING_USERNAME = "CROSSBROWSERTESTING_USERNAME";
	public static String CROSSBROWSERTESTING_AUTOMATE_KEY = "CROSSBROWSERTESTING_AUTOMATE_KEY";
	public static String CROSSBROWSERTESTING_ANDROID_MOBILE_DEVICES = "CROSSBROWSERTESTING_ANDROID_MOBILE_DEVICES";
	public static String CROSSBROWSERTESTING_ANDROID_TABLET_DEVICES = "CROSSBROWSERTESTING_ANDROID_TABLET_DEVICES";
	public static String CROSSBROWSERTESTING_IOS_MOBILE_DEVICES = "CROSSBROWSERTESTING_IOS_MOBILE_DEVICES";
	public static String CROSSBROWSERTESTING_IOS_TABLET_DEVICES = "CROSSBROWSERTESTING_IOS_TABLET_DEVICES";

	public static String ANDROID_DEVICE_ID = "ANDROID_DEVICE_ID";
	public static String IOS_DEVICE_NAME = "IOS_DEVICE_NAME";
	public static String IOS_DEVICE_UDID = "IOS_DEVICE_UDID";
	public static String RUN_APPIUM_SCRIPT_IN_MOBILE_MODE_ON_DESKTOP = "RUN_APPIUM_SCRIPT_IN_MOBILE_MODE_ON_DESKTOP";
	public static String RUN_MOBILE_SCRIPT_ON_LOCAL_IPHONE_REAL_DEVICE = "RUN_MOBILE_SCRIPT_ON_LOCAL_IPHONE_REAL_DEVICE";

	public static String TEST_ENV = "testEnv";

	public static String WEB_HUB_URL = "WEB_HUB_URL";
	public static String IOS_HUB_URL = "IOS_HUB_URL";
	public static String ANDROID_HUB_URL = "ANDROID_HUB_URL";

}
